spring:
  application:
    name: query-service

server:
  port: 8083

services:
  metrics-url: http://localhost:8081
  logs-url: http://localhost:8082

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

app:
  query:
    max-page-size: 200